### ISSUE TITLE
Akopolis unstake asking for 3 ETH

### ISSUE THREAD

**Issue by s3cryptostuff** [akropolisio/akropolis#21]
![Screenshot 2021-02-24 095137](https://user-images.githubusercontent.com/74742059/109060055-d8603b00-76dc-11eb-9ce6-acdd08f2f44f.jpg)
![Screenshot 2021-02-24 095152](https://user-images.githubusercontent.com/74742059/109060076-e0b87600-76dc-11eb-8848-f3dbf73ba56a.jpg)

**Comment by in19farkt** [comment]
@s3cryptostuff We calculated the real gas consumption for unstake from 0xf121285fdba3989765532478663cfab170adfb43 in block # 11922400 (24 Feb 2020, 22:06:11 + UTC).

As a result, we received 356,256 gas units. Considering the average gas price of 150 Gwei, this corresponds to 0.053 ETH.

Therefore, we can conclude that the problem lies in the Metamask extension, which in some cases greatly overestimates the gas limit.
